import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NProgressProvider from "@/components/Common/NProgressProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " max-w-screen-xl mx-auto overflow-x-hidden w-full p-2"}>
        <NProgressProvider>
          {children}
        </NProgressProvider>
      </body>
    </html>
  );
}
